FROM israelhikingmap/graphhopper:10.0

ENV OSM_FILE_URL=https://download.geofabrik.de/europe/turkey-latest.osm.pbf
ENV GRAPH_CACHE_DIR=/data/graph-cache
ENV OSM_FILE=/data/map.osm.pbf
ENV CONFIG_FILE=/data/config.yml

RUN mkdir -p /data

RUN curl -o $OSM_FILE $OSM_FILE_URL

#COPY graphhopper-config.yml $CONFIG_FILE
#RUN ./graphhopper.sh import $OSM_FILE

EXPOSE 8989 8989

ENTRYPOINT ./graphhopper.sh -i $OSM_FILE
